// Generated by com.aib.orm.tools.dbgen.DbGenerator.class at Sat Apr 05 12:44:00 FET 2014
// generated file: do not modify
package com.aib.orm;

import com.aib.orm.dbobject.DbObject;
import com.aib.orm.dbobject.ForeignKeyViolationException;
import com.aib.orm.dbobject.Triggers;
import java.sql.*;
import java.util.ArrayList;

public class Industry extends DbObject  {
    private static Triggers activeTriggers = null;
    private Integer industryId = null;
    private String descr = null;

    public Industry(Connection connection) {
        super(connection, "industry", "industry_id");
        setColumnNames(new String[]{"industry_id", "descr"});
    }

    public Industry(Connection connection, Integer industryId, String descr) {
        super(connection, "industry", "industry_id");
        setNew(industryId.intValue() <= 0);
//        if (industryId.intValue() != 0) {
            this.industryId = industryId;
//        }
        this.descr = descr;
    }

    public DbObject loadOnId(int id) throws SQLException, ForeignKeyViolationException {
        Industry industry = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT industry_id,descr FROM industry WHERE industry_id=" + id;
        try {
            ps = getConnection().prepareStatement(stmt);
            rs = ps.executeQuery();
            if (rs.next()) {
                industry = new Industry(getConnection());
                industry.setIndustryId(new Integer(rs.getInt(1)));
                industry.setDescr(rs.getString(2));
                industry.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return industry;
    }

    protected void insert() throws SQLException, ForeignKeyViolationException {
         if (getTriggers() != null) {
             getTriggers().beforeInsert(this);
         }
         PreparedStatement ps = null;
         String stmt =
                "INSERT INTO industry ("+(getIndustryId().intValue()!=0?"industry_id,":"")+"descr) values("+(getIndustryId().intValue()!=0?"?,":"")+"?)";
         try {
             ps = getConnection().prepareStatement(stmt);
             int n = 0;
             if (getIndustryId().intValue()!=0) {
                 ps.setObject(++n, getIndustryId());
             }
             ps.setObject(++n, getDescr());
             ps.execute();
         } finally {
             if (ps != null) ps.close();
         }
         ResultSet rs = null;
         if (getIndustryId().intValue()==0) {
             stmt = "SELECT max(industry_id) FROM industry";
             try {
                 ps = getConnection().prepareStatement(stmt);
                 rs = ps.executeQuery();
                 if (rs.next()) {
                     setIndustryId(new Integer(rs.getInt(1)));
                 }
             } finally {
                 try {
                     if (rs != null) rs.close();
                 } finally {
                     if (ps != null) ps.close();
                 }
             }
         }
         setNew(false);
         setWasChanged(false);
         if (getTriggers() != null) {
             getTriggers().afterInsert(this);
         }
    }

    public void save() throws SQLException, ForeignKeyViolationException {
        if (isNew()) {
            insert();
        } else {
            if (getTriggers() != null) {
                getTriggers().beforeUpdate(this);
            }
            PreparedStatement ps = null;
            String stmt =
                    "UPDATE industry " +
                    "SET descr = ?" + 
                    " WHERE industry_id = " + getIndustryId();
            try {
                ps = getConnection().prepareStatement(stmt);
                ps.setObject(1, getDescr());
                ps.execute();
            } finally {
                if (ps != null) ps.close();
            }
            setWasChanged(false);
            if (getTriggers() != null) {
                getTriggers().afterUpdate(this);
            }
        }
    }

    public void delete() throws SQLException, ForeignKeyViolationException {
        if (getTriggers() != null) {
            getTriggers().beforeDelete(this);
        }
        {// delete cascade from compindustry
            Compindustry[] records = (Compindustry[])Compindustry.load(getConnection(),"industry_id = " + getIndustryId(),null);
            for (int i = 0; i<records.length; i++) {
                Compindustry compindustry = records[i];
                compindustry.delete();
            }
        }
        {// delete cascade from locindustry
            Locindustry[] records = (Locindustry[])Locindustry.load(getConnection(),"industry_id = " + getIndustryId(),null);
            for (int i = 0; i<records.length; i++) {
                Locindustry locindustry = records[i];
                locindustry.delete();
            }
        }
        {// delete cascade from peopleindustry
            Peopleindustry[] records = (Peopleindustry[])Peopleindustry.load(getConnection(),"industry_id = " + getIndustryId(),null);
            for (int i = 0; i<records.length; i++) {
                Peopleindustry peopleindustry = records[i];
                peopleindustry.delete();
            }
        }
        PreparedStatement ps = null;
        String stmt =
                "DELETE FROM industry " +
                "WHERE industry_id = " + getIndustryId();
        try {
            ps = getConnection().prepareStatement(stmt);
            ps.execute();
        } finally {
            if (ps != null) ps.close();
        }
        setIndustryId(new Integer(-getIndustryId().intValue()));
        if (getTriggers() != null) {
            getTriggers().afterDelete(this);
        }
    }

    public boolean isDeleted() {
        return (getIndustryId().intValue() < 0);
    }

    public static DbObject[] load(Connection con,String whereCondition,String orderCondition) throws SQLException {
        ArrayList lst = new ArrayList();
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT industry_id,descr FROM industry " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                " WHERE " + whereCondition : "") +
                ((orderCondition != null && orderCondition.length() > 0) ?
                " ORDER BY " + orderCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            while (rs.next()) {
                DbObject dbObj;
                lst.add(dbObj=new Industry(con,new Integer(rs.getInt(1)),rs.getString(2)));
                dbObj.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        Industry[] objects = new Industry[lst.size()];
        for (int i = 0; i < lst.size(); i++) {
            Industry industry = (Industry) lst.get(i);
            objects[i] = industry;
        }
        return objects;
    }

    public static boolean exists(Connection con, String whereCondition) throws SQLException {
        if (con == null) {
            return true;
        }
        boolean ok = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT industry_id FROM industry " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                "WHERE " + whereCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            ok = rs.next();
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return ok;
    }

    //public String toString() {
    //    return getIndustryId() + getDelimiter();
    //}

    public Integer getPK_ID() {
        return industryId;
    }

    public void setPK_ID(Integer id) throws ForeignKeyViolationException {
        boolean prevIsNew = isNew();
        setIndustryId(id);
        setNew(prevIsNew);
    }

    public Integer getIndustryId() {
        return industryId;
    }

    public void setIndustryId(Integer industryId) throws ForeignKeyViolationException {
        setWasChanged(this.industryId != null && this.industryId != industryId);
        this.industryId = industryId;
        setNew(industryId.intValue() == 0);
    }

    public String getDescr() {
        return descr;
    }

    public void setDescr(String descr) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.descr != null && !this.descr.equals(descr));
        this.descr = descr;
    }
    public Object[] getAsRow() {
        Object[] columnValues = new Object[2];
        columnValues[0] = getIndustryId();
        columnValues[1] = getDescr();
        return columnValues;
    }

    public static void setTriggers(Triggers triggers) {
        activeTriggers = triggers;
    }

    public static Triggers getTriggers() {
        return activeTriggers;
    }

    //for SOAP exhange
    @Override
    public void fillFromString(String row) throws ForeignKeyViolationException, SQLException {
        String[] flds = splitStr(row, delimiter);
        try {
            setIndustryId(Integer.parseInt(flds[0]));
        } catch(NumberFormatException ne) {
            setIndustryId(null);
        }
        setDescr(flds[1]);
    }
}
