// Generated by com.xlend.orm.tools.dbgen.DbGenerator.class at Fri Jun 28 16:12:16 EEST 2013
// generated file: do not modify
package com.aib.orm;

import com.aib.orm.dbobject.DbObject;
import com.aib.orm.dbobject.ForeignKeyViolationException;
import com.aib.orm.dbobject.Triggers;
import java.sql.*;
import java.util.ArrayList;

public class Link extends DbObject  {
    private static Triggers activeTriggers = null;
    private Integer linkId = null;
    private String url = null;

    public Link(Connection connection) {
        super(connection, "link", "link_id");
        setColumnNames(new String[]{"link_id", "url"});
    }

    public Link(Connection connection, Integer linkId, String url) {
        super(connection, "link", "link_id");
        setNew(linkId.intValue() <= 0);
//        if (linkId.intValue() != 0) {
            this.linkId = linkId;
//        }
        this.url = url;
    }

    public DbObject loadOnId(int id) throws SQLException, ForeignKeyViolationException {
        Link link = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT link_id,url FROM link WHERE link_id=" + id;
        try {
            ps = getConnection().prepareStatement(stmt);
            rs = ps.executeQuery();
            if (rs.next()) {
                link = new Link(getConnection());
                link.setLinkId(new Integer(rs.getInt(1)));
                link.setUrl(rs.getString(2));
                link.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return link;
    }

    protected void insert() throws SQLException, ForeignKeyViolationException {
         if (getTriggers() != null) {
             getTriggers().beforeInsert(this);
         }
         PreparedStatement ps = null;
         String stmt =
                "INSERT INTO link ("+(getLinkId().intValue()!=0?"link_id,":"")+"url) values("+(getLinkId().intValue()!=0?"?,":"")+"?)";
         try {
             ps = getConnection().prepareStatement(stmt);
             int n = 0;
             if (getLinkId().intValue()!=0) {
                 ps.setObject(++n, getLinkId());
             }
             ps.setObject(++n, getUrl());
             ps.execute();
         } finally {
             if (ps != null) ps.close();
         }
         ResultSet rs = null;
         if (getLinkId().intValue()==0) {
             stmt = "SELECT max(link_id) FROM link";
             try {
                 ps = getConnection().prepareStatement(stmt);
                 rs = ps.executeQuery();
                 if (rs.next()) {
                     setLinkId(new Integer(rs.getInt(1)));
                 }
             } finally {
                 try {
                     if (rs != null) rs.close();
                 } finally {
                     if (ps != null) ps.close();
                 }
             }
         }
         setNew(false);
         setWasChanged(false);
         if (getTriggers() != null) {
             getTriggers().afterInsert(this);
         }
    }

    public void save() throws SQLException, ForeignKeyViolationException {
        if (isNew()) {
            insert();
        } else {
            if (getTriggers() != null) {
                getTriggers().beforeUpdate(this);
            }
            PreparedStatement ps = null;
            String stmt =
                    "UPDATE link " +
                    "SET url = ?" + 
                    " WHERE link_id = " + getLinkId();
            try {
                ps = getConnection().prepareStatement(stmt);
                ps.setObject(1, getUrl());
                ps.execute();
            } finally {
                if (ps != null) ps.close();
            }
            setWasChanged(false);
            if (getTriggers() != null) {
                getTriggers().afterUpdate(this);
            }
        }
    }

    public void delete() throws SQLException, ForeignKeyViolationException {
        if (getTriggers() != null) {
            getTriggers().beforeDelete(this);
        }
        {// delete cascade from peoplelink
            Peoplelink[] records = (Peoplelink[])Peoplelink.load(getConnection(),"link_id = " + getLinkId(),null);
            for (int i = 0; i<records.length; i++) {
                Peoplelink peoplelink = records[i];
                peoplelink.delete();
            }
        }
        {// delete cascade from loclink
            Loclink[] records = (Loclink[])Loclink.load(getConnection(),"link_id = " + getLinkId(),null);
            for (int i = 0; i<records.length; i++) {
                Loclink loclink = records[i];
                loclink.delete();
            }
        }
        {// delete cascade from complink
            Complink[] records = (Complink[])Complink.load(getConnection(),"link_id = " + getLinkId(),null);
            for (int i = 0; i<records.length; i++) {
                Complink complink = records[i];
                complink.delete();
            }
        }
        PreparedStatement ps = null;
        String stmt =
                "DELETE FROM link " +
                "WHERE link_id = " + getLinkId();
        try {
            ps = getConnection().prepareStatement(stmt);
            ps.execute();
        } finally {
            if (ps != null) ps.close();
        }
        setLinkId(new Integer(-getLinkId().intValue()));
        if (getTriggers() != null) {
            getTriggers().afterDelete(this);
        }
    }

    public boolean isDeleted() {
        return (getLinkId().intValue() < 0);
    }

    public static DbObject[] load(Connection con,String whereCondition,String orderCondition) throws SQLException {
        ArrayList lst = new ArrayList();
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT link_id,url FROM link " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                " WHERE " + whereCondition : "") +
                ((orderCondition != null && orderCondition.length() > 0) ?
                " ORDER BY " + orderCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            while (rs.next()) {
                DbObject dbObj;
                lst.add(dbObj=new Link(con,new Integer(rs.getInt(1)),rs.getString(2)));
                dbObj.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        Link[] objects = new Link[lst.size()];
        for (int i = 0; i < lst.size(); i++) {
            Link link = (Link) lst.get(i);
            objects[i] = link;
        }
        return objects;
    }

    public static boolean exists(Connection con, String whereCondition) throws SQLException {
        if (con == null) {
            return true;
        }
        boolean ok = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT link_id FROM link " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                "WHERE " + whereCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            ok = rs.next();
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return ok;
    }

    //public String toString() {
    //    return getLinkId() + getDelimiter();
    //}

    public Integer getPK_ID() {
        return linkId;
    }

    public void setPK_ID(Integer id) throws ForeignKeyViolationException {
        boolean prevIsNew = isNew();
        setLinkId(id);
        setNew(prevIsNew);
    }

    public Integer getLinkId() {
        return linkId;
    }

    public void setLinkId(Integer linkId) throws ForeignKeyViolationException {
        setWasChanged(this.linkId != null && this.linkId != linkId);
        this.linkId = linkId;
        setNew(linkId.intValue() == 0);
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.url != null && !this.url.equals(url));
        this.url = url;
    }
    public Object[] getAsRow() {
        Object[] columnValues = new Object[2];
        columnValues[0] = getLinkId();
        columnValues[1] = getUrl();
        return columnValues;
    }

    public static void setTriggers(Triggers triggers) {
        activeTriggers = triggers;
    }

    public static Triggers getTriggers() {
        return activeTriggers;
    }

    //for SOAP exhange
    @Override
    public void fillFromString(String row) throws ForeignKeyViolationException, SQLException {
        String[] flds = splitStr(row, delimiter);
        try {
            setLinkId(Integer.parseInt(flds[0]));
        } catch(NumberFormatException ne) {
            setLinkId(null);
        }
        setUrl(flds[1]);
    }
}
