// Generated by com.xlend.orm.tools.dbgen.DbGenerator.class at Mon May 06 19:00:21 EEST 2013
// generated file: do not modify
package com.aib.orm;

import com.aib.orm.dbobject.DbObject;
import com.aib.orm.dbobject.ForeignKeyViolationException;
import com.aib.orm.dbobject.Triggers;
import java.sql.*;
import java.util.ArrayList;

public class Company_aibpublic extends DbObject  {
    private static Triggers activeTriggers = null;
    private Integer companyAibpublicId = null;
    private Integer companyId = null;
    private Integer aibpublicId = null;

    public Company_aibpublic(Connection connection) {
        super(connection, "company_aibpublic", "company_aibpublic_id");
        setColumnNames(new String[]{"company_aibpublic_id", "company_id", "aibpublic_id"});
    }

    public Company_aibpublic(Connection connection, Integer companyAibpublicId, Integer companyId, Integer aibpublicId) {
        super(connection, "company_aibpublic", "company_aibpublic_id");
        setNew(companyAibpublicId.intValue() <= 0);
//        if (companyAibpublicId.intValue() != 0) {
            this.companyAibpublicId = companyAibpublicId;
//        }
        this.companyId = companyId;
        this.aibpublicId = aibpublicId;
    }

    public DbObject loadOnId(int id) throws SQLException, ForeignKeyViolationException {
        Company_aibpublic company_aibpublic = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT company_aibpublic_id,company_id,aibpublic_id FROM company_aibpublic WHERE company_aibpublic_id=" + id;
        try {
            ps = getConnection().prepareStatement(stmt);
            rs = ps.executeQuery();
            if (rs.next()) {
                company_aibpublic = new Company_aibpublic(getConnection());
                company_aibpublic.setCompanyAibpublicId(new Integer(rs.getInt(1)));
                company_aibpublic.setCompanyId(new Integer(rs.getInt(2)));
                company_aibpublic.setAibpublicId(new Integer(rs.getInt(3)));
                company_aibpublic.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return company_aibpublic;
    }

    protected void insert() throws SQLException, ForeignKeyViolationException {
         if (getTriggers() != null) {
             getTriggers().beforeInsert(this);
         }
         PreparedStatement ps = null;
         String stmt =
                "INSERT INTO company_aibpublic ("+(getCompanyAibpublicId().intValue()!=0?"company_aibpublic_id,":"")+"company_id,aibpublic_id) values("+(getCompanyAibpublicId().intValue()!=0?"?,":"")+"?,?)";
         try {
             ps = getConnection().prepareStatement(stmt);
             int n = 0;
             if (getCompanyAibpublicId().intValue()!=0) {
                 ps.setObject(++n, getCompanyAibpublicId());
             }
             ps.setObject(++n, getCompanyId());
             ps.setObject(++n, getAibpublicId());
             ps.execute();
         } finally {
             if (ps != null) ps.close();
         }
         ResultSet rs = null;
         if (getCompanyAibpublicId().intValue()==0) {
             stmt = "SELECT max(company_aibpublic_id) FROM company_aibpublic";
             try {
                 ps = getConnection().prepareStatement(stmt);
                 rs = ps.executeQuery();
                 if (rs.next()) {
                     setCompanyAibpublicId(new Integer(rs.getInt(1)));
                 }
             } finally {
                 try {
                     if (rs != null) rs.close();
                 } finally {
                     if (ps != null) ps.close();
                 }
             }
         }
         setNew(false);
         setWasChanged(false);
         if (getTriggers() != null) {
             getTriggers().afterInsert(this);
         }
    }

    public void save() throws SQLException, ForeignKeyViolationException {
        if (isNew()) {
            insert();
        } else {
            if (getTriggers() != null) {
                getTriggers().beforeUpdate(this);
            }
            PreparedStatement ps = null;
            String stmt =
                    "UPDATE company_aibpublic " +
                    "SET company_id = ?, aibpublic_id = ?" + 
                    " WHERE company_aibpublic_id = " + getCompanyAibpublicId();
            try {
                ps = getConnection().prepareStatement(stmt);
                ps.setObject(1, getCompanyId());
                ps.setObject(2, getAibpublicId());
                ps.execute();
            } finally {
                if (ps != null) ps.close();
            }
            setWasChanged(false);
            if (getTriggers() != null) {
                getTriggers().afterUpdate(this);
            }
        }
    }

    public void delete() throws SQLException, ForeignKeyViolationException {
        if (getTriggers() != null) {
            getTriggers().beforeDelete(this);
        }
        PreparedStatement ps = null;
        String stmt =
                "DELETE FROM company_aibpublic " +
                "WHERE company_aibpublic_id = " + getCompanyAibpublicId();
        try {
            ps = getConnection().prepareStatement(stmt);
            ps.execute();
        } finally {
            if (ps != null) ps.close();
        }
        setCompanyAibpublicId(new Integer(-getCompanyAibpublicId().intValue()));
        if (getTriggers() != null) {
            getTriggers().afterDelete(this);
        }
    }

    public boolean isDeleted() {
        return (getCompanyAibpublicId().intValue() < 0);
    }

    public static DbObject[] load(Connection con,String whereCondition,String orderCondition) throws SQLException {
        ArrayList lst = new ArrayList();
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT company_aibpublic_id,company_id,aibpublic_id FROM company_aibpublic " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                " WHERE " + whereCondition : "") +
                ((orderCondition != null && orderCondition.length() > 0) ?
                " ORDER BY " + orderCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            while (rs.next()) {
                DbObject dbObj;
                lst.add(dbObj=new Company_aibpublic(con,new Integer(rs.getInt(1)),new Integer(rs.getInt(2)),new Integer(rs.getInt(3))));
                dbObj.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        Company_aibpublic[] objects = new Company_aibpublic[lst.size()];
        for (int i = 0; i < lst.size(); i++) {
            Company_aibpublic company_aibpublic = (Company_aibpublic) lst.get(i);
            objects[i] = company_aibpublic;
        }
        return objects;
    }

    public static boolean exists(Connection con, String whereCondition) throws SQLException {
        if (con == null) {
            return true;
        }
        boolean ok = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT company_aibpublic_id FROM company_aibpublic " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                "WHERE " + whereCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            ok = rs.next();
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return ok;
    }

    //public String toString() {
    //    return getCompanyAibpublicId() + getDelimiter();
    //}

    public Integer getPK_ID() {
        return companyAibpublicId;
    }

    public void setPK_ID(Integer id) throws ForeignKeyViolationException {
        boolean prevIsNew = isNew();
        setCompanyAibpublicId(id);
        setNew(prevIsNew);
    }

    public Integer getCompanyAibpublicId() {
        return companyAibpublicId;
    }

    public void setCompanyAibpublicId(Integer companyAibpublicId) throws ForeignKeyViolationException {
        setWasChanged(this.companyAibpublicId != null && this.companyAibpublicId != companyAibpublicId);
        this.companyAibpublicId = companyAibpublicId;
        setNew(companyAibpublicId.intValue() == 0);
    }

    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) throws SQLException, ForeignKeyViolationException {
        if (companyId!=null && !Company.exists(getConnection(),"company_id = " + companyId)) {
            throw new ForeignKeyViolationException("Can't set company_id, foreign key violation: comppublic_company_fk");
        }
        setWasChanged(this.companyId != null && !this.companyId.equals(companyId));
        this.companyId = companyId;
    }

    public Integer getAibpublicId() {
        return aibpublicId;
    }

    public void setAibpublicId(Integer aibpublicId) throws SQLException, ForeignKeyViolationException {
        if (aibpublicId!=null && !Aibpublic.exists(getConnection(),"aibpublic_id = " + aibpublicId)) {
            throw new ForeignKeyViolationException("Can't set aibpublic_id, foreign key violation: comppublic_aibpublic_fk");
        }
        setWasChanged(this.aibpublicId != null && !this.aibpublicId.equals(aibpublicId));
        this.aibpublicId = aibpublicId;
    }
    public Object[] getAsRow() {
        Object[] columnValues = new Object[3];
        columnValues[0] = getCompanyAibpublicId();
        columnValues[1] = getCompanyId();
        columnValues[2] = getAibpublicId();
        return columnValues;
    }

    public static void setTriggers(Triggers triggers) {
        activeTriggers = triggers;
    }

    public static Triggers getTriggers() {
        return activeTriggers;
    }

    //for SOAP exhange
    @Override
    public void fillFromString(String row) throws ForeignKeyViolationException, SQLException {
        String[] flds = splitStr(row, delimiter);
        try {
            setCompanyAibpublicId(Integer.parseInt(flds[0]));
        } catch(NumberFormatException ne) {
            setCompanyAibpublicId(null);
        }
        try {
            setCompanyId(Integer.parseInt(flds[1]));
        } catch(NumberFormatException ne) {
            setCompanyId(null);
        }
        try {
            setAibpublicId(Integer.parseInt(flds[2]));
        } catch(NumberFormatException ne) {
            setAibpublicId(null);
        }
    }
}
