// Generated by com.xlend.orm.tools.dbgen.DbGenerator.class at Tue Jun 04 09:31:12 EEST 2013
// generated file: do not modify
package com.aib.orm;

import com.aib.orm.dbobject.DbObject;
import com.aib.orm.dbobject.ForeignKeyViolationException;
import com.aib.orm.dbobject.Triggers;
import java.sql.*;
import java.util.ArrayList;

public class Comppublic extends DbObject  {
    private static Triggers activeTriggers = null;
    private Integer comppublicId = null;
    private Integer companyId = null;
    private Integer aibpublicId = null;

    public Comppublic(Connection connection) {
        super(connection, "comppublic", "comppublic_id");
        setColumnNames(new String[]{"comppublic_id", "company_id", "aibpublic_id"});
    }

    public Comppublic(Connection connection, Integer comppublicId, Integer companyId, Integer aibpublicId) {
        super(connection, "comppublic", "comppublic_id");
        setNew(comppublicId.intValue() <= 0);
//        if (comppublicId.intValue() != 0) {
            this.comppublicId = comppublicId;
//        }
        this.companyId = companyId;
        this.aibpublicId = aibpublicId;
    }

    public DbObject loadOnId(int id) throws SQLException, ForeignKeyViolationException {
        Comppublic comppublic = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT comppublic_id,company_id,aibpublic_id FROM comppublic WHERE comppublic_id=" + id;
        try {
            ps = getConnection().prepareStatement(stmt);
            rs = ps.executeQuery();
            if (rs.next()) {
                comppublic = new Comppublic(getConnection());
                comppublic.setComppublicId(new Integer(rs.getInt(1)));
                comppublic.setCompanyId(new Integer(rs.getInt(2)));
                comppublic.setAibpublicId(new Integer(rs.getInt(3)));
                comppublic.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return comppublic;
    }

    protected void insert() throws SQLException, ForeignKeyViolationException {
         if (getTriggers() != null) {
             getTriggers().beforeInsert(this);
         }
         PreparedStatement ps = null;
         String stmt =
                "INSERT INTO comppublic ("+(getComppublicId().intValue()!=0?"comppublic_id,":"")+"company_id,aibpublic_id) values("+(getComppublicId().intValue()!=0?"?,":"")+"?,?)";
         try {
             ps = getConnection().prepareStatement(stmt);
             int n = 0;
             if (getComppublicId().intValue()!=0) {
                 ps.setObject(++n, getComppublicId());
             }
             ps.setObject(++n, getCompanyId());
             ps.setObject(++n, getAibpublicId());
             ps.execute();
         } finally {
             if (ps != null) ps.close();
         }
         ResultSet rs = null;
         if (getComppublicId().intValue()==0) {
             stmt = "SELECT max(comppublic_id) FROM comppublic";
             try {
                 ps = getConnection().prepareStatement(stmt);
                 rs = ps.executeQuery();
                 if (rs.next()) {
                     setComppublicId(new Integer(rs.getInt(1)));
                 }
             } finally {
                 try {
                     if (rs != null) rs.close();
                 } finally {
                     if (ps != null) ps.close();
                 }
             }
         }
         setNew(false);
         setWasChanged(false);
         if (getTriggers() != null) {
             getTriggers().afterInsert(this);
         }
    }

    public void save() throws SQLException, ForeignKeyViolationException {
        if (isNew()) {
            insert();
        } else {
            if (getTriggers() != null) {
                getTriggers().beforeUpdate(this);
            }
            PreparedStatement ps = null;
            String stmt =
                    "UPDATE comppublic " +
                    "SET company_id = ?, aibpublic_id = ?" + 
                    " WHERE comppublic_id = " + getComppublicId();
            try {
                ps = getConnection().prepareStatement(stmt);
                ps.setObject(1, getCompanyId());
                ps.setObject(2, getAibpublicId());
                ps.execute();
            } finally {
                if (ps != null) ps.close();
            }
            setWasChanged(false);
            if (getTriggers() != null) {
                getTriggers().afterUpdate(this);
            }
        }
    }

    public void delete() throws SQLException, ForeignKeyViolationException {
        if (getTriggers() != null) {
            getTriggers().beforeDelete(this);
        }
        PreparedStatement ps = null;
        String stmt =
                "DELETE FROM comppublic " +
                "WHERE comppublic_id = " + getComppublicId();
        try {
            ps = getConnection().prepareStatement(stmt);
            ps.execute();
        } finally {
            if (ps != null) ps.close();
        }
        setComppublicId(new Integer(-getComppublicId().intValue()));
        if (getTriggers() != null) {
            getTriggers().afterDelete(this);
        }
    }

    public boolean isDeleted() {
        return (getComppublicId().intValue() < 0);
    }

    public static DbObject[] load(Connection con,String whereCondition,String orderCondition) throws SQLException {
        ArrayList lst = new ArrayList();
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT comppublic_id,company_id,aibpublic_id FROM comppublic " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                " WHERE " + whereCondition : "") +
                ((orderCondition != null && orderCondition.length() > 0) ?
                " ORDER BY " + orderCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            while (rs.next()) {
                DbObject dbObj;
                lst.add(dbObj=new Comppublic(con,new Integer(rs.getInt(1)),new Integer(rs.getInt(2)),new Integer(rs.getInt(3))));
                dbObj.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        Comppublic[] objects = new Comppublic[lst.size()];
        for (int i = 0; i < lst.size(); i++) {
            Comppublic comppublic = (Comppublic) lst.get(i);
            objects[i] = comppublic;
        }
        return objects;
    }

    public static boolean exists(Connection con, String whereCondition) throws SQLException {
        if (con == null) {
            return true;
        }
        boolean ok = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT comppublic_id FROM comppublic " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                "WHERE " + whereCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            ok = rs.next();
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return ok;
    }

    //public String toString() {
    //    return getComppublicId() + getDelimiter();
    //}

    public Integer getPK_ID() {
        return comppublicId;
    }

    public void setPK_ID(Integer id) throws ForeignKeyViolationException {
        boolean prevIsNew = isNew();
        setComppublicId(id);
        setNew(prevIsNew);
    }

    public Integer getComppublicId() {
        return comppublicId;
    }

    public void setComppublicId(Integer comppublicId) throws ForeignKeyViolationException {
        setWasChanged(this.comppublicId != null && this.comppublicId != comppublicId);
        this.comppublicId = comppublicId;
        setNew(comppublicId.intValue() == 0);
    }

    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) throws SQLException, ForeignKeyViolationException {
        if (companyId!=null && !Company.exists(getConnection(),"company_id = " + companyId)) {
            throw new ForeignKeyViolationException("Can't set company_id, foreign key violation: comppublic_company_fk");
        }
        setWasChanged(this.companyId != null && !this.companyId.equals(companyId));
        this.companyId = companyId;
    }

    public Integer getAibpublicId() {
        return aibpublicId;
    }

    public void setAibpublicId(Integer aibpublicId) throws SQLException, ForeignKeyViolationException {
        if (aibpublicId!=null && !Aibpublic.exists(getConnection(),"aibpublic_id = " + aibpublicId)) {
            throw new ForeignKeyViolationException("Can't set aibpublic_id, foreign key violation: comppublic_aibpublic_fk");
        }
        setWasChanged(this.aibpublicId != null && !this.aibpublicId.equals(aibpublicId));
        this.aibpublicId = aibpublicId;
    }
    public Object[] getAsRow() {
        Object[] columnValues = new Object[3];
        columnValues[0] = getComppublicId();
        columnValues[1] = getCompanyId();
        columnValues[2] = getAibpublicId();
        return columnValues;
    }

    public static void setTriggers(Triggers triggers) {
        activeTriggers = triggers;
    }

    public static Triggers getTriggers() {
        return activeTriggers;
    }

    //for SOAP exhange
    @Override
    public void fillFromString(String row) throws ForeignKeyViolationException, SQLException {
        String[] flds = splitStr(row, delimiter);
        try {
            setComppublicId(Integer.parseInt(flds[0]));
        } catch(NumberFormatException ne) {
            setComppublicId(null);
        }
        try {
            setCompanyId(Integer.parseInt(flds[1]));
        } catch(NumberFormatException ne) {
            setCompanyId(null);
        }
        try {
            setAibpublicId(Integer.parseInt(flds[2]));
        } catch(NumberFormatException ne) {
            setAibpublicId(null);
        }
    }
}
